"""Add dialog_messages table

Revision ID: db862e0be9c3
Revises: dac32999bcfd
Create Date: 2026-09-14 13:51:55.666922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db862e0be9c3'
down_revision: Union[str, None] = 'dac32999bcfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialog_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dialog_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dialog_messages_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dialog_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dialog_messages_user_id'))

    op.drop_table('dialog_messages')
    # ### end Alembic commands ###
